---
- name: Install Apache on Ubuntu hosts
  hosts: linux_hosts 
  become: true       

  tasks:
    - name: Install apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure Apache2 service is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

- name: Install IIS on Windows hosts
  hosts: windows_hosts 
  become: true         

  tasks:
    - name: Install Web-Server (IIS) feature
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Ensure World Wide Web Publishing Service (IIS) is running and enabled
      ansible.windows.win_service:
        name: W3SVC 
        state: started
        enabled: true